version: "3"
services:
  frontend:
    ports:
      - "3030:3030"
    command: bash -c "yarn && yarn build && yarn start"

  websocket:
    command: bash -c "yarn && yarn start"

  backend:
    command: bash -c ". launch_prod_server.sh"
